name: content-service
resolver:
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 3s
root: /
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: pages_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=pages_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
services:
  album-manager:
    server: marathon.mesos
    service: service=_album-manager._tcp
    expose_external: true
    healthcheck: true
    oss_port: 12001
