name: uploader
resolver:
  host: kube-dns.kube-system.svc.cluster.local
  ttl: 1s
root: /usr/share/nginx/html/
namespace: nginx-mra
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: pages_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=pages_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
services:
  album-manager:
    server: nginx-mra.svc.cluster.local
    service: service=_https._tcp.album-manager
    expose_external: true
    healthcheck: true
    oss_port: 12001
  resizer:
    server: nginx-mra.svc.cluster.local
    service: service=_https._tcp.photoresizer
    expose_external: false
    healthcheck: true
    healthcheck_uri: /healthcheck
    oss_port: 12005
